config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :employees do
    collection do
      get 'search', to: 'employees#search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :employees

    after_save :index_employees_elasticsearch

    def index_employees_elasticsearch
        employees.find_each { |emp| emp.__elasticsearch__.index_document }
    end

end

app/models/employee.rb
require 'elasticsearch/model'

class Employee < ApplicationRecord
  include Elasticsearch::Model # add methods like search
  include Elasticsearch::Model::Callbacks # add callbacks
  
  validates_uniqueness_of :name
  belongs_to :department

  index_name Rails.application.class.parent_name.underscore
  # document_type self.name.downcase throws issue for elasticsearch 7+

  settings index: { number_of_shards: 1 } do
    mapping dynamic: false do
      indexes :name, analyzer: 'english'
      indexes :address, analyzer: 'keyword'
    end
  end

  # To index a virtual field, one which is not stored in DB.
  def as_indexed_json(options = {})
    self.as_json( only: [:name, :address] )
    # :method_name is either a symbol or an array of symbols corresponding to method names in your model.
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['name^3', 'address']
          }
        },
        highlight: {
          pre_tags: ['<mark>'],
          post_tags: ['</mark>'],
          fields: {
            name: {},
            address: {},
          }
        },
      }
    ).results
  end
  # 3 is weight of name field i.e, it's 3 times as important.

  def self.search_w_recomm(query)
    # term suggester
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['name^3', 'address']
          }
        },
        suggest: {
          text: query,
          name: {
            term: {
              size: 1,
              field: :name
            },
          },
          address: {
            term: {
              size: 1,
              field: :address
            }
          }
        }
      }
    ).results
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employees = Employee.find(params[:id])
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def search
  #   @employees = params[:query].nil? ? [] : Employee.__elasticsearch__.search(
  #                                                                         query: {
  #                                                                           query_string: {
  #                                                                             query: "#{params[:query]}*"
  #                                                                           }
  #                                                                         }
  #                                                                         ).results
  # end

  def search
    @employees = []
    binding.pry
    if params[:query].present?
      @employees = Employee.search(params[:query])
    end
    Rails.logger.info "Employee: #{@employees[0]}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.fetch(:employee, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Search', search_employees_path %>
<br>
<br>
<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/search.html.erb
<h1>Employee Search</h1>

<%= form_for search_employees_path, method: :post, remote: true do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "search", name: nil %>
  </p>
<% end %>

<ul>
  <% @employees.each do |employee| %>
    <li>
      <h3>
        <%= link_to employee.name, controller: "employees", action: "show", id: employee._id%>
      </h3>
    </li>
  <% end %>
</ul>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>
<br>
<br>
<table>
    <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Department</th>
    </tr>
    <tr>
        <td>
            <%= @employee.name %>
        </td>
        <td>
            <%= @employee.address %>
        </td>
        <td>
            <%= @employee.department %>
        </td>
    </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EsearchApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>